#!/bin/bash

set -ex

NO_PROXY="localhost,$(hostname -A | tr ' ' ','),$(hostname -I | tr ' ' ','),$NO_PROXY"
NO_PROXY="${NO_PROXY/,,/,}"

export NO_PROXY

regress-stack plan
regress-stack setup
regress-stack test
